[package]
name = "dockerbox"
version = "0.1.0"
description = "Utility to backup a docker volume (or any folder) to Dropbox, once or periodically."
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
chrono = "0.4"
clap = {version = "4", features = ["derive"]}
dotenvy = "0.15"
dropbox-sdk = { version = "0.15", default-features = false, features = ["dbx_files", "default_client"] }
job_scheduler_ng = "2"
