[package]
name = "awsbck"
version = "0.1.0"
description = "Utility to backup a folder to AWS S3, once or periodically."
authors = ["Valentin Bersier <vbersier@gmail.com>"]
repository = "https://github.com/beeb/awsbck-rs"
license = "MIT"
edition = "2021"

[dependencies]
anyhow = "1"
aws-config = "0.54"
aws-sdk-s3 = "0.24"
aws-smithy-http = "0.54"
chrono = "0.4"
clap = { version = "4", features = ["derive", "env"] }
cron = "0.12"
dotenvy = "0.15"
flate2 = "1"
tar = "0.4"
tempfile = "3"
tokio = { version = "1", features = ["full"] }
tokio-cron-scheduler = { version = "0.9", features = ["signal"] }

[dev-dependencies]
ctor = "0.1"
