[package]
name = "dockerbck"
version = "0.1.0"
description = "Utility to backup a docker volume (or any folder) to AWS S3, once or periodically."
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
aws-config = "0.54"
aws-sdk-s3 = "0.24"
aws-smithy-http = "0.54"
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
cron = "0.12"
dotenvy = "0.15"
flate2 = "1"
tar = "0.4"
tempfile = "3"
tokio = { version = "1", features = ["full"] }
tokio-cron-scheduler = "0.9"

[dev-dependencies]
ctor = "0.1"
