FROM gcr.io/distroless/static-debian11

ARG TARGETOS
ARG TARGETARCH

WORKDIR /awsbck

# Copy the binary with correct permissions (requires buildx?)
COPY --chmod=0755 ./${TARGETOS}_${TARGETARCH}/awsbck .

# We use entrypoint to allow passing arguments to the binary using `CMD`
ENTRYPOINT ["/awsbck/awsbck"]
