name: Remove old artifacts

on:
  schedule:
    - cron: '23 1 * * *' # Every day at 1:23am
  workflow_dispatch:

jobs:
  remove-old-artifacts:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: 7 days
          skip-recent: 50
