name: Lint

on:
  push:
  pull_request:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Check
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: |
        rustup component add rustfmt clippy
        cargo check
        cargo fmt --all -- --check
        cargo clippy -- -Dwarnings

