name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Check
    steps:
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - uses: actions/checkout@v5
      - run: |
          cargo check --locked
          cargo fmt --all -- --check
          cargo clippy -- -Dwarnings

  tests:
    if: github.ref_type == 'tag' || startsWith(github.ref, 'refs/pull/')
    needs: lint
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions/checkout@v5
      - run: cargo test
